### ISSUE TITLE
Add dark theme support

### ISSUE THREAD

**Issue by silverAndroid** [ieee-uottawa/ieeeuottawa.ca#99]
There's a CSS media query called [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) which tells the browser if the user enabled OS-wide dark-mode. We can leverage this to enable dark mode for our website.

**Comment by iDuckDark** [comment]
[IEEE uOttawa Student Branch - Dark Mode.pdf](https://github.com/ieee-uottawa/ieeeuottawa.ca/files/3209970/IEEE.uOttawa.Student.Branch.-.Dark.Mode.pdf)
How it looks like with the dark mode reader chrome extension
